#!/bin/bash

temp_output_file=$(mktemp)
result="$(
    count_images=( $(wc -l test-new-images.data) );
    while read -r line; do
        values=($line)
        echo "img/${values[0]}.bmp";
    done < test-new-images.data | ../pokedex-client > "$temp_output_file" 2>&1 | tail -n $count_images
    )"
    
# Imprimer la sortie du programme pour déboguer
cat "$temp_output_file"
rm -f "$temp_output_file"